name: Continous Integration Tests
on: [ push, pull_request ]
jobs:
  jenkins-agent-golang-rhel7:
    name: Jenkins agent Go (RHEL7)
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/golang/docker
        run: |
          docker build --tag agent-go-test-rhel7 --file Dockerfile.rhel7 .

  jenkins-agent-golang-ubi8:
    name: Jenkins agent Go (UBI8)
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/golang/docker
        run: |
          docker build --tag agent-go-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-maven:
    name: Jenkins agent Maven (UBI8)
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/maven/docker
        run: |
            docker build --tag agent-maven-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusUsername=developer \
              --build-arg nexusPassword=s3cr3t \
              .

# jenkins-agent-nodejs10-angular:
#   name: Jenkins agent NodeJS 10 - Angular
#   runs-on: ubuntu-18.04
#   steps:
#     -
#       name: Checkout repository
#       uses: actions/checkout@v2.0.0
#     -
#       name: Build docker image
#       working-directory: common/jenkins-agents/nodejs10-angular/docker
#       run: |
#           docker build --tag agent-nodejs10-angular-test \
#             --build-arg nexusUrl=https://nexus.example.com \
#             --build-arg nexusAuth=developer:s3cr3t \
#             .

  jenkins-agent-nodejs12-rhel7:
    name: Jenkins agent NodeJS 12 (RHEL7)
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs12/docker
        run: |
            docker build --tag agent-nodejs12-test-rhel7 --file Dockerfile.rhel7 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-nodejs12-ubi8:
    name: Jenkins agent NodeJS 12 (UBI8)
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs12/docker
        run: |
            docker build --tag agent-nodejs12-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-python:
    name: Jenkins agent Python
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Build docker image
        working-directory: common/jenkins-agents/python/docker
        run: |
            docker build --tag agent-python-test \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusUsername=developer \
              --build-arg nexusPassword=s3cr3t \
              .

# jenkins-agent-scala:
#   name: Jenkins agent Scala
#   runs-on: ubuntu-18.04
#   steps:
#     -
#       name: Checkout repository
#       uses: actions/checkout@v2.0.0
#     -
#       name: Build docker image
#       working-directory: common/jenkins-agents/scala/docker
#       run: |
#           docker build --tag agent-scala-test \
#             --build-arg nexusUrl=https://nexus.example.com \
#             --build-arg nexusUsername=developer \
#             --build-arg nexusPassword=s3cr3t \
#             .

  compile-go-tests:
    name: Verify Go tests are formatted and can be compiled
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2.0.0
      -
        name: Verify all Go files are formatted with gofmt
        working-directory: tests
        run: |
          unformatted=$(gofmt -l .)
          [ -z "$unformatted" ] && exit 0
          echo >&2 "Go files must be formatted with gofmt. Please run:"
          for fn in $unformatted; do
              echo >&2 "  gofmt -w $fn"
          done
          exit 1
      -
        name: Verify all Go tests can be compiled
        working-directory: tests
        run: |
          go test -c ./be-fe-mono-repo-plain
          go test -c ./be-gateway-nginx
          go test -c ./be-golang-plain
          go test -c ./be-java-springboot
          go test -c ./be-python-flask
          go test -c ./be-scala-play
          go test -c ./be-typescript-express
          go test -c ./docker-plain
          go test -c ./ds-jupyter-notebook
          go test -c ./ds-ml-service
          go test -c ./ds-rshiny
          go test -c ./e2e-cypress
          go test -c ./e2e-spock-geb
          go test -c ./fe-angular
          go test -c ./fe-ionic
          go test -c ./ods-document-gen-svc
          go test -c ./ods-provisioning-app
          go test -c ./release-manager


#   test:
#     name: Docker plain provisioning
#     runs-on: ubuntu-16.04
#     steps:
#       - 
#         name: GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: jq . <<< "${GITHUB_CONTEXT}"
#       - 
#         name: Checkout QuickStarters repository
#         uses: actions/checkout@v2.0.0
#         with:
#           fetch-depth: 0
#           path: ods-quickstarters
#       - 
#         name: Checkout ODS Core
#         uses: actions/checkout@v2.0.0
#         with:
#           fetch-depth: 0
#           repository: opendevstack/ods-core
#           ref: master
#           path: ods-core
#       - 
#         name: Checkout ODS Jenkins Shared Library
#         uses: actions/checkout@v2.0.0
#         with:
#           fetch-depth: 0
#           repository: BIX-Digital/ods-jenkins-shared-library
#           ref: invalid/curl-http-only
#           path: ods-jenkins-shared-library
#       -
#         name: Setup Go 1.13
#         uses: actions/setup-go@v1.0.0
#         with:      
#           version: 1.13
#       -
#         name: Download OpenShift Client
#         run: |
#           wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
#           tar -xzvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
#           sudo mv openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin/oc
#       -
#         name: Download Tailor
#         run: |
#           curl -LO "https://github.com/opendevstack/tailor/releases/download/v0.11.0/tailor-linux-amd64"
#           chmod +x tailor-linux-amd64
#           sudo mv tailor-linux-amd64 /usr/local/bin/tailor
#       -
#          name: Tailor version
#          run: tailor version
#       -
#          name: OpenShift client version
#          run: oc version
#       -
#          name: jq version
#          run: jq --version
#       -
#          name: golang version
#          run: go version
#       -
#          name: Docker version
#          run: docker --version
#       -
#          name: Network before changes
#          run: ifconfig
#       -
#          name: Configure docker network and insecure registries
#          run: ls -la && ls -la ./tests && ./tests/scripts/apply-docker-settings.sh
#          working-directory: ${{  format('{0}/ods-core', github.workspace) }}
#       -
#          name: Start OC cluster
#          run: oc cluster up --base-dir=${HOME}/openshift.local.clusterup --routing-suffix 172.17.0.1.nip.io --public-hostname 172.17.0.1 --enable=centos-imagestreams --enable=persistent-volumes --enable=registry --enable=router
#       -
#          name: Login into the cluster
#          run: oc login -u system:admin
#       -
#         name: Create test infrastructure
#         run: |
#           mkdir -p ods-config
#           ./tests/scripts/recreate-test-infrastructure.sh
#         working-directory: ${{  format('{0}/ods-core', github.workspace) }}
#       -
#         name: Test setup
#         run: make setup-tests
#         working-directory: ${{  format('{0}/ods-quickstarters/tests', github.workspace) }}
#       -
#         name: Run tests
#         run: make test
#         working-directory: ${{  format('{0}/ods-quickstarters/tests', github.workspace) }}
