name: Continous Integration Tests
on: [ push, pull_request ]
jobs:

  jenkins-agent-golang-ubi8:
    name: Jenkins agent Go (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/golang/docker
        run: |
          docker build --tag agent-go-test-ubi8 --file Dockerfile.ubi8 \
            --build-arg goDistributionUrl=https://go.dev/dl/go1.20.4.linux-amd64.tar.gz \
            .

  jenkins-agent-jdk-ubi8:
    name: Jenkins agent JDK (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/jdk/docker
        run: |
            docker build --tag agent-jdk-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusUsername=developer \
              --build-arg nexusPassword=s3cr3t \
              .

  jenkins-agent-nodejs16-ubi8:
    name: Jenkins agent NodeJS 16 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs16/docker
        run: |
            docker build --tag agent-nodejs16-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-nodejs18-ubi8:
    name: Jenkins agent NodeJS 18 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs18/docker
        run: |
            docker build --tag agent-nodejs18-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-nodejs20-ubi8:
    name: Jenkins agent NodeJS 20 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs20/docker
        run: |
            docker build --tag agent-nodejs20-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-python-ubi8:
    name: Jenkins agent Python (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/python/docker
        run: |
          docker build --tag agent-python-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-terraform-ubi8:
    name: Jenkins agent Terraform (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/terraform/docker
        run: |
          docker build --tag agent-terraform-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-terraform-2306-ubi8:
    name: Jenkins agent Terraform 2306 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/terraform-2306/docker
        run: |
          docker build --tag agent-terraform-2306-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-scala-ubi8:
    name: Jenkins agent Scala (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.1.1
      -
        name: Build docker image
        working-directory: common/jenkins-agents/scala/docker
        run: |
          docker build --tag agent-scala-test-ubi8 --file Dockerfile.ubi8 \
             --build-arg nexusUrl=https://nexus.example.com \
             --build-arg nexusUsername=developer \
             --build-arg nexusPassword=s3cr3t \
             .
