name: Continous Integration Tests
on: [ push, pull_request ]
jobs:

  jenkins-agent-golang-ubi8:
    name: Jenkins agent Go (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/golang/docker
        run: |
          docker build --tag agent-go-test-ubi8 --file Dockerfile.ubi8 \
            --build-arg goDistributionUrl=https://go.dev/dl/go1.23.0.linux-amd64.tar.gz \
            --build-arg golangciVersion=v1.60.1 \
            .

  jenkins-agent-jdk-ubi8:
    name: Jenkins agent JDK (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/jdk/docker
        run: |
            docker build --tag agent-jdk-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusUsername=developer \
              --build-arg nexusPassword=s3cr3t \
              .

  jenkins-agent-nodejs18-ubi8:
    name: Jenkins agent NodeJS 18 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs18/docker
        run: |
            docker build --tag agent-nodejs18-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-nodejs20-ubi8:
    name: Jenkins agent NodeJS 20 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs20/docker
        run: |
            docker build --tag agent-nodejs20-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-nodejs22-ubi8:
    name: Jenkins agent NodeJS 22 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/nodejs22/docker
        run: |
            docker build --tag agent-nodejs22-test-ubi8 --file Dockerfile.ubi8 \
              --build-arg nexusUrl=https://nexus.example.com \
              --build-arg nexusAuth=developer:s3cr3t \
              .

  jenkins-agent-python-ubi8:
    name: Jenkins agent Python (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/python/docker
        run: |
          docker build --tag agent-python-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-rust-ubi8:
    name: Jenkins agent Rust (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/rust/docker
        run: |
          docker build --tag agent-rust-test-ubi8 --file Dockerfile.ubi8 \
            --build-arg rustVersion=1.81.0 \
            --build-arg rustToolchain=x86_64-unknown-linux-gnu \
            --build-arg cargoNextestVersion=0.9.78 \
            --build-arg cargoLlvmCovVersion=0.6.13 \
            --build-arg cargoGenerateVersion=0.22.0 \
            --build-arg cargoDenyVersion=0.16.1 \
            .

  jenkins-agent-terraform-2306-ubi8:
    name: Jenkins agent Terraform 2306 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/terraform-2306/docker
        run: |
          docker build --tag agent-terraform-2306-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-terraform-2408-ubi8:
    name: Jenkins agent Terraform 2408 (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/terraform-2408/docker
        run: |
          docker build --tag agent-terraform-2408-test-ubi8 --file Dockerfile.ubi8 .

  jenkins-agent-scala-ubi8:
    name: Jenkins agent Scala (UBI8)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4.2.2
      -
        name: Build docker image
        working-directory: common/jenkins-agents/scala/docker
        run: |
          docker build --tag agent-scala-test-ubi8 --file Dockerfile.ubi8 \
             --build-arg nexusUrl=https://nexus.example.com \
             --build-arg nexusUsername=developer \
             --build-arg nexusPassword=s3cr3t \
             .
